# Generated by Django 5.1.2 on 2024-11-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
        ('tickets_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ticket',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='tickets_app.ticket'),
        ),
    ]
