# Generated by Django 5.1.2 on 2024-11-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_ticket_subtask_assigned_profile_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ticket',
            new_name='tickets',
        ),
    ]
