# Generated by Django 5.1.2 on 2024-11-17 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_rename_ticket_profile_tickets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='due_date',
            new_name='dueDate',
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.ManyToManyField(related_name='tickets', to='profile_app.assigned'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='subtasks',
            field=models.ManyToManyField(related_name='ticket_subtasks', to='profile_app.subtask'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask_tickets', to='profile_app.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='progress',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], max_length=255),
        ),
    ]
