# Generated by Django 5.1.2 on 2024-11-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='profile_app.contact'),
        ),
    ]
