# Generated by Django 5.1.2 on 2024-11-17 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_alter_ticket_options_rename_due_date_ticket_duedate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='assigned_to',
            new_name='assignedTo',
        ),
        migrations.AlterField(
            model_name='assigned',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_items', to='profile_app.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='progress',
            field=models.CharField(max_length=255),
        ),
    ]
