# Generated by Django 5.1.2 on 2024-11-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_alter_profile_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='backgroundColor',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='contact',
            name='isSelected',
            field=models.BooleanField(default=False),
        ),
    ]
