# Generated by Django 5.1.2 on 2024-11-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_rename_assigned_to_ticket_assignedto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tickets',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='profile_app.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assignedTo',
            field=models.ManyToManyField(related_name='assigned_contacts', to='profile_app.assigned'),
        ),
    ]
