# Generated by Django 5.1.2 on 2024-11-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0006_contact_backgroundcolor_contact_isselected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='backgroundColor',
            field=models.CharField(default='#000000', max_length=20),
        ),
    ]
