# Generated by Django 5.1.2 on 2024-11-20 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0006_alter_profile_tickets_alter_ticket_assignedto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='subtask_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='subtasks',
        ),
        migrations.AlterField(
            model_name='subtask',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='profile_app.ticket'),
        ),
    ]
