# Generated by Django 5.1.2 on 2024-11-08 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bg_color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('identifier', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='tickets', to='tickets_app.assigneduser')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='profile_app.profile')),
                ('subtasks', models.ManyToManyField(blank=True, related_name='tickets', to='tickets_app.subtask')),
            ],
        ),
    ]
